import { ArrowUpRight, BarChart3, Check, ChevronRight, CircleDollarSign, Leaf, Plus, Sparkles, Tag, X } from 'lucide-react';
import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { getGetMarketPriceQueryKey, getListFarmerListingsQueryKey, getListListingsQueryKey, getListOrdersQueryKey, useApproveBulkOrder, useCreateListing, useGetCropRecommendations, useGetFarmerDashboard, useGetMarketPrice, useListFarmerListings, useListOrders, useMarkListingSoldOut, useUpdateListing } from '@workspace/api-client-react';
import type { Listing } from '@workspace/api-client-react';
import { EmptyState, ErrorState, formatMoney, PageIntro, SkeletonCards, VoiceAssistButton } from '@/components/app-shell';

const FARMER_ID = 1;

export default function FarmerDashboard() {
  const queryClient = useQueryClient();
  const [showCreate, setShowCreate] = useState(false);
  const [crop, setCrop] = useState('tomato');
  const dashboardQuery = useGetFarmerDashboard();
  const listingsQuery = useListFarmerListings(FARMER_ID);
  const ordersQuery = useListOrders({ role: 'farmer' });
  const recommendationsQuery = useGetCropRecommendations();
  const priceQuery = useGetMarketPrice(crop, { query: { enabled: Boolean(crop), queryKey: getGetMarketPriceQueryKey(crop) } });
  const createListing = useCreateListing();
  const updateListing = useUpdateListing();
  const soldOut = useMarkListingSoldOut();
  const approveOrder = useApproveBulkOrder();
  const dashboard = dashboardQuery.data;
  const pendingOrders = (ordersQuery.data ?? []).filter((order) => order.type === 'bulk' && order.status === 'order_placed');

  function invalidateListings() {
    queryClient.invalidateQueries({ queryKey: getListFarmerListingsQueryKey(FARMER_ID) });
    queryClient.invalidateQueries({ queryKey: getListListingsQueryKey() });
  }

  function createNewListing(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    createListing.mutate({ data: { farmerId: FARMER_ID, crop: String(form.get('crop')), variety: String(form.get('variety')), location: String(form.get('location')), photoUrl: String(form.get('photoUrl') || ''), householdPrice: Number(form.get('householdPrice')), householdQuantity: Number(form.get('householdQuantity')), bulkPrice: Number(form.get('bulkPrice')), bulkQuantity: Number(form.get('bulkQuantity')) } }, {
      onSuccess: () => { invalidateListings(); setShowCreate(false); },
    });
  }

  if (dashboardQuery.isError) return <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><ErrorState onRetry={() => void dashboardQuery.refetch()} /></div>;

  return (
    <div className="mx-auto max-w-7xl px-4 pb-24 pt-10 sm:px-6 lg:px-8">
      <PageIntro eyebrow="farmer workspace · Tuesday, 18 June" title="Good morning, Ramesh." description="Here is the shape of your farm business today. Clear numbers, useful signals, no noise." action={<div className="flex items-center gap-2"><button type="button" data-testid="button-new-listing" onClick={() => setShowCreate(true)} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground shadow-sm transition hover:-translate-y-0.5"><Plus size={17} /> New listing</button><VoiceAssistButton label="Hear new listing instructions" text="Add a new crop listing with household price, bulk price, and available quantity." /></div>} />
      {dashboardQuery.isLoading ? <div className="mt-10 grid gap-4 sm:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="skeleton h-32 rounded-2xl" />)}</div> : <div className="mt-10 grid gap-4 sm:grid-cols-3"><MetricCard label="sales this season" value={formatMoney(dashboard?.totalSales ?? 0)} note="+12% from last season" icon={CircleDollarSign} /><MetricCard label="net farm profit" value={formatMoney(dashboard?.totalProfit ?? 0)} note="after collection costs" icon={Leaf} /><MetricCard label="best-selling crop" value={dashboard?.bestSellingCrop ?? '—'} note={`${dashboard?.pendingApprovals ?? 0} orders need you`} icon={BarChart3} /></div>}

      <div className="mt-8 grid gap-6 lg:grid-cols-[1.25fr_.75fr]">
        <section className="rounded-2xl border border-border bg-card p-5 shadow-[var(--shadow-sm)] sm:p-7">
          <div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">your season, at a glance</p><h2 className="mt-2 font-serif text-2xl font-semibold">Sales rhythm</h2></div><span className="rounded-full bg-secondary px-3 py-1.5 text-xs font-semibold text-primary">Last 6 weeks</span></div>
          <div className="mt-8 flex h-52 items-end gap-2 sm:gap-4">{(dashboard?.chart ?? []).map((item, index) => { const max = Math.max(...(dashboard?.chart ?? [{ value: 1 }]).map((point) => point.value), 1); return <div key={item.label} className="flex flex-1 flex-col items-center gap-2"><span className="font-mono text-[9px] text-muted-foreground">{formatMoney(item.value)}</span><div className="relative flex h-36 w-full items-end overflow-hidden rounded-t-lg bg-muted"><div className={`w-full rounded-t-lg bg-primary transition-all duration-700 ${index === (dashboard?.chart.length ?? 1) - 1 ? 'bg-accent' : ''}`} style={{ height: `${Math.max(8, (item.value / max) * 100)}%` }} /></div><span className="font-mono text-[9px] uppercase text-muted-foreground">{item.label}</span></div> })}</div>
        </section>
        <section className="rounded-2xl border border-border bg-primary p-6 text-primary-foreground shadow-[var(--shadow-sm)]"><div className="flex size-10 items-center justify-center rounded-xl bg-primary-foreground/10"><Sparkles size={19} /></div><p className="mt-6 font-mono text-[10px] uppercase tracking-[.2em] text-primary-foreground/65">next good move</p><h2 className="mt-2 font-serif text-2xl font-semibold">Plant with the pull of the market.</h2><p className="mt-3 text-sm leading-6 text-primary-foreground/70">Demand is shifting toward shorter harvest cycles. See which crops could make your next acre count.</p><button type="button" data-testid="button-view-recommendations" onClick={() => document.getElementById('recommendations')?.scrollIntoView({ behavior: 'smooth' })} className="mt-6 flex items-center gap-2 text-sm font-semibold text-[#f4d77d]">See recommendations <ArrowUpRight size={16} /></button></section>
      </div>

      <div className="mt-8 grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
        <section id="recommendations" className="rounded-2xl border border-border bg-card p-5 shadow-[var(--shadow-sm)] sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">field intelligence</p><h2 className="mt-2 font-serif text-2xl font-semibold">Planting ideas</h2></div><Leaf size={20} className="text-primary" /></div><div className="mt-5 space-y-3">{recommendationsQuery.isLoading ? [1, 2, 3].map((item) => <div key={item} className="skeleton h-20 rounded-xl" />) : (recommendationsQuery.data ?? []).slice(0, 3).map((recommendation) => <div key={recommendation.crop} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">{recommendation.crop}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{recommendation.reason}</p></div><span className="font-mono text-sm font-semibold text-accent">{recommendation.score}/10</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-accent" style={{ width: `${recommendation.score * 10}%` }} /></div></div>)}</div></section>
        <section className="rounded-2xl border border-border bg-card p-5 shadow-[var(--shadow-sm)] sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">smart pricing</p><h2 className="mt-2 font-serif text-2xl font-semibold">Price with context</h2></div><select data-testid="select-pricing-crop" value={crop} onChange={(event) => setCrop(event.target.value)} className="h-10 rounded-lg border border-input bg-background px-3 text-sm outline-none"><option value="tomato">Tomato</option><option value="onion">Onion</option><option value="wheat">Wheat</option><option value="rice">Rice</option></select></div>{priceQuery.isLoading ? <div className="skeleton mt-6 h-40 rounded-xl" /> : priceQuery.data ? <div className="mt-6 grid gap-4 sm:grid-cols-[.9fr_1.1fr]"><div className="rounded-xl bg-secondary/60 p-5"><p className="text-xs text-muted-foreground">current market reference</p><p className="mt-2 font-serif text-4xl font-semibold text-primary">{formatMoney(priceQuery.data.marketPrice)}</p><p className="mt-3 text-xs font-semibold text-accent">{priceQuery.data.demandLevel} demand · {priceQuery.data.demandVolume} kg nearby</p></div><div className="rounded-xl border border-border p-5"><div className="flex justify-between text-xs"><span className="text-muted-foreground">sustainable range</span><span className="font-semibold">{formatMoney(priceQuery.data.sustainableLow)} — {formatMoney(priceQuery.data.sustainableHigh)}</span></div><div className="relative mt-6 h-2 rounded-full bg-muted"><span className="absolute left-[25%] right-[17%] h-2 rounded-full bg-accent" /><span className="absolute left-[63%] top-1/2 size-4 -translate-y-1/2 rounded-full border-2 border-card bg-primary shadow" /></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{priceQuery.data.recommendation}</p></div></div> : <p className="mt-6 text-sm text-muted-foreground">Market guidance is unavailable for this crop.</p>}</section>
      </div>

      <section className="mt-8 rounded-2xl border border-border bg-card p-5 shadow-[var(--shadow-sm)] sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">your harvest board</p><h2 className="mt-2 font-serif text-2xl font-semibold">Active listings</h2></div><span className="font-mono text-xs text-muted-foreground">{(listingsQuery.data ?? []).length} live</span></div>{listingsQuery.isLoading ? <div className="mt-6"><SkeletonCards count={2} /></div> : (listingsQuery.data ?? []).length === 0 ? <div className="mt-6"><EmptyState title="Your board is quiet" description="Add your first listing so nearby households can find the next harvest." action={<button type="button" data-testid="button-empty-new-listing" onClick={() => setShowCreate(true)} className="rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Add a listing</button>} /></div> : <div className="mt-6 grid gap-3">{(listingsQuery.data ?? []).map((listing: Listing) => <div key={listing.id} data-testid={`row-listing-${listing.id}`} className="flex flex-col gap-4 rounded-xl border border-border p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-secondary text-primary"><Tag size={18} /></div><div><p className="font-semibold">{listing.variety} {listing.crop}</p><p className="mt-1 text-xs text-muted-foreground">{formatMoney(listing.householdPrice)} / {listing.unit} · {listing.demandLevel} demand</p></div></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${listing.soldOut ? 'bg-destructive/10 text-destructive' : 'bg-secondary text-primary'}`}>{listing.soldOut ? 'Sold out' : 'Live'}</span>{!listing.soldOut && <button type="button" data-testid={`button-sold-out-${listing.id}`} onClick={() => soldOut.mutate({ listingId: listing.id }, { onSuccess: invalidateListings })} className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:bg-muted">Mark sold out</button>}<button type="button" data-testid={`button-price-${listing.id}`} onClick={() => updateListing.mutate({ listingId: listing.id, data: { householdPrice: Math.round(listing.householdPrice * 1.03) } }, { onSuccess: invalidateListings })} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">+3% price</button></div></div>)}</div>}</section>

      <section className="mt-8 rounded-2xl border border-border bg-card p-5 shadow-[var(--shadow-sm)] sm:p-7"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">needs your answer</p><h2 className="mt-2 font-serif text-2xl font-semibold">Bulk approvals</h2></div><span className="rounded-full bg-accent/10 px-3 py-1 text-xs font-semibold text-accent">{pendingOrders.length} pending</span></div>{pendingOrders.length === 0 ? <p className="mt-6 text-sm text-muted-foreground">No bulk orders are waiting. We will place them here when a household or business wants more of your harvest.</p> : <div className="mt-6 space-y-3">{pendingOrders.map((order) => <div key={order.id} className="flex flex-col gap-3 rounded-xl border border-border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{order.quantity} kg {order.crop} · {order.buyerName}</p><p className="mt-1 text-xs text-muted-foreground">{order.hub} · {formatMoney(order.total)}</p></div><div className="flex gap-2"><button type="button" data-testid={`button-reject-order-${order.id}`} onClick={() => approveOrder.mutate({ orderId: order.id, data: { decision: 'rejected' } }, { onSuccess: () => queryClient.invalidateQueries({ queryKey: getListOrdersQueryKey({ role: 'farmer' }) }) })} className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:bg-muted">Decline</button><button type="button" data-testid={`button-approve-order-${order.id}`} onClick={() => approveOrder.mutate({ orderId: order.id, data: { decision: 'accepted' } }, { onSuccess: () => queryClient.invalidateQueries({ queryKey: getListOrdersQueryKey({ role: 'farmer' }) }) })} className="flex items-center gap-1 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground"><Check size={14} /> Accept order</button></div></div>)}</div>}</section>

      {showCreate && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-primary/35 p-4 backdrop-blur-sm"><form onSubmit={createNewListing} className="relative my-8 w-full max-w-2xl rounded-3xl border border-border bg-card p-6 shadow-[var(--shadow-lg)] sm:p-8"><button type="button" data-testid="button-close-listing-form" onClick={() => setShowCreate(false)} className="absolute right-5 top-5 grid size-9 place-items-center rounded-full bg-muted"><X size={17} /></button><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">new harvest</p><h2 className="mt-2 font-serif text-3xl font-semibold">Tell the market what is ready.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="Crop" name="crop" placeholder="Tomato" /><Field label="Variety" name="variety" placeholder="Desi red" /><Field label="Location" name="location" placeholder="Nashik" /><Field label="Photo URL (optional)" name="photoUrl" placeholder="https://…" /><Field label="Household price" name="householdPrice" type="number" placeholder="48" /><Field label="Household quantity" name="householdQuantity" type="number" placeholder="1" /><Field label="Bulk price" name="bulkPrice" type="number" placeholder="38" /><Field label="Bulk quantity" name="bulkQuantity" type="number" placeholder="25" /></div><button type="submit" data-testid="button-save-listing" disabled={createListing.isPending} className="mt-7 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-semibold text-primary-foreground disabled:opacity-60">{createListing.isPending ? 'Publishing…' : 'Publish listing'} <ChevronRight size={17} /></button>{createListing.isError && <p className="mt-3 text-center text-xs text-destructive">Could not publish this listing. Please check the details.</p>}</form></div>}
    </div>
  );
}

function MetricCard({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof CircleDollarSign }) {
  return <div className="rounded-2xl border border-border bg-card p-5 shadow-[var(--shadow-sm)]"><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">{label}</p><Icon size={18} className="text-accent" /></div><p className="mt-5 font-serif text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></div>;
}

function Field({ label, name, placeholder, type = 'text' }: { label: string; name: string; placeholder: string; type?: string }) {
  return <label className="block text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}<input required={name !== 'photoUrl'} name={name} type={type} placeholder={placeholder} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm font-normal normal-case tracking-normal outline-none focus:ring-2 focus:ring-ring" /></label>;
}
